"""
User model for Todo Intelligence Platform.

Managed by Better Auth library (Stage 7).
Per constitution.md section 7.1, this table stores user accounts.
"""

from sqlmodel import SQLModel, Field, Index
from typing import Optional
from datetime import datetime


class User(SQLModel, table=True):
    """
    User account model.

    Managed by Better Auth library for authentication.
    Password never stored in plain text (hashed only).
    """

    __tablename__ = "users"

    # Primary Key
    id: str = Field(primary_key=True, max_length=255)  # Generated by Better Auth

    # User credentials
    email: str = Field(unique=True, nullable=False, max_length=255, index=True)
    password_hash: Optional[str] = Field(default=None, max_length=255)

    # Timestamps (UTC per constitution.md section 7.4)
    created_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
    updated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)

    class Config:
        """SQLModel configuration."""
        json_schema_extra = {
            "example": {
                "id": "user_123abc",
                "email": "user@example.com",
                "created_at": "2025-12-27T10:30:00Z",
                "updated_at": "2025-12-27T10:30:00Z"
            }
        }


# Index definitions (per database/schema.md section "Table 1: users")
# Note: SQLModel will create these via Alembic migrations

__all__ = ["User"]
